---
# tasks file for common
#- name: configure / Update yum packeages
#  yum:
#    name: '*'
#    state: latest
#    update_cache: yes

- name: check install ja_JP.utf8
  shell: bash -lc "locale -a | grep ja_JP.utf8"
  register: LANG_import_check
  failed_when: LANG_import_check.rc not in [0,1]
  changed_when: False

- name: import ja_JP.utf8
  shell: localedef -f  UTF-8 -i ja_JP ja_JP.UTF-8
  when: LANG_import_check.rc == 1

- name: set server encoding
  lineinfile:
    path: /etc/locale.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
   - { regexp: '^LANG=', line: 'LANG="ja_JP.UTF-8"'}
   - { regexp: '^LANGUAGE=', line: 'LANGUAGE="ja_JP:ja"'}
   - { regexp: '^LC_ALL=', line: 'LC_ALL="ja_JP.UTF-8"'} 

- name: check server encoding ja_JP.UTF-8
  shell: bash -lc "locale | grep LANG=ja_JP.UTF-8"
  register: LANG_set_check
  failed_when: LANG_set_check.rc not in [0,1]
  changed_when: False

- name: set server encoding
  shell: source /etc/locale.conf
  when: LANG_set_check.rc == 1

- name: configure /Import EPEL Repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes
